name: naver_map_js2dart
version: 0.0.1
description: >
  With that package you will be able to use Google Maps JavaScript API from Dart
  scripts.
homepage: https://github.com/a14n/dart-google-maps
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  js: ^0.6.0
  meta: ^1.1.2
dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  dart_style: ^1.3.6
  html: ^0.14.0+3
  http: ^0.12.1
  path: ^1.7.0